spring.config.import=optional:file:.env[.properties]

spring.application.name=authentication

server.port=8080
server.servlet.context-path=/auth

spring.mongodb.uri=${MONGODB_URI}

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=${JWT_EXPIRES_IN}